FROM node:12 as builder

WORKDIR /app
COPY ./package.json ./
RUN yarn install
COPY . .
RUN yarn run build

FROM nginx
EXPOSE 3000
COPY ./nginx/default.conf /etc/nginx/conf.d/default.conf
COPY ./nginx/nginx-selfsigned.crt /etc/nginx/conf.d/nginx-selfsigned.crt
COPY ./nginx/nginx-selfsigned.key /etc/nginx/conf.d/nginx-selfsigned.key
COPY --from=builder /app/build /usr/share/nginx/html
CMD ["nginx", "-g", "daemon off;"]