export const LOGIN_ERROR_MAIL = 'LOGIN_ERROR_MAIL';
export const LOGIN_ERROR_CREDENTIALS = 'LOGIN_ERROR_CREDENTIALS';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const SERVER_ERROR = 'SERVER_ERROR';
